Task-37857: Add quarantine page
exoplatform/ecms pull request #1058
Opened 2020-12-22 09:02 UTC by AzmiTouil

2020-12-22 09:33 UTC, ahamdi commented
@azayati @AzmiTouil Why are latest PRs on Develop ?

2020-12-22 13:52 UTC, azayati requested changes
See review

2020-12-22 13:52 UTC, azayati commented on apps/pom.xml
> +    <module>portlet-quarantine</module>
```suggestion
    <module>portlet-dlp-quarantine</module>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/package.json
> +  "name": "quarantine",
```suggestion
  "name": "dlp-quarantine",
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/package.json
> +  "description": "eXo Quarantine",
```suggestion
  "description": "eXo Dlp Quarantine",
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/resources/locale/portlet/quarantine_fr.properties
> +documents.quarantine.label=Quarantaine
```suggestion
documents.dlp.quarantine.label=Quarantaine
```
Put the other labels

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/package.json
> +    "lint": "eslint --fix ./src/main/webapp/vue-apps/quarantine/components/QuarantineApp.vue ./src/main/webapp/vue-app/quarantine/*.js",
```suggestion
    "lint": "eslint --fix ./src/main/webapp/vue-apps/dlp-quarantine/components/DlpQuarantineApp.vue ./src/main/webapp/vue-app/dlp-quarantine/*.js",
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/pom.xml
> +  <artifactId>ecms-apps-portlet-quarantine</artifactId>
```suggestion
  <artifactId>ecms-apps-portlet-dlp-quarantine</artifactId>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/pom.xml
> +  <name>eXo PLF:: Quarantine Admin Portlet</name>
```suggestion
  <name>eXo PLF:: Dlp Quarantine Admin Portlet</name>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/pom.xml
> +  <description>eXo DMS Portlet Java Content: Quarantine Admin</description>
```suggestion
  <description>eXo DMS Portlet Java Content: Dlp Quarantine Admin</description>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/pom.xml
> +    <finalName>quarantine</finalName>
```suggestion
    <finalName>dlp-quarantine</finalName>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/conf/configuration.xml
> +  <import>war:/conf/quarantine/portal/portal-configuration.xml</import>
```suggestion
  <import>war:/conf/dlp-quarantine/portal/portal-configuration.xml</import>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/resources/locale/navigation/group/platform/administrators_en.properties
> +administration.quarantine.label=Quarantine
```suggestion
administration.dlp.quarantine.label=Quarantine
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/resources/locale/navigation/group/platform/administrators_fr.properties
> +administration.quarantine.label=Quarantaine
```suggestion
administration.dlp.quarantine.label=Quarantaine
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/resources/locale/portlet/quarantine_en.properties
> +documents.quarantine.label=Quarantine
```suggestion
documents.dlp.quarantine.label=Quarantine
```
same for other labels

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/conf/quarantine/portal/group/platform/administrators/pages.xml
> +      <title>Quarantine Administration</title>
```suggestion
      <title>Dlp Quarantine Administration</title>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/portlet.xml
> +    <portlet-name>quarantinePortlet</portlet-name>
```suggestion
    <portlet-name>dlpQuarantinePortlet</portlet-name>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/portlet.xml
> +    <display-name xml:lang="EN">Quarantine portlet</display-name>
```suggestion
    <display-name xml:lang="EN">Dlp Quarantine portlet</display-name>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/portlet.xml
> +      <title>Quarantine portlet for eXo Platform</title>
```suggestion
      <title>Dlp Quarantine portlet for eXo Platform</title>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/gatein-resources.xml
> +    <name>quarantine</name>
```suggestion
    <name>dlp-quarantine</name>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/conf/quarantine/portal/group/platform/administrators/navigation.xml
> +      <uri>quarantine</uri>
```suggestion
      <uri>dlp-quarantine</uri>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/conf/quarantine/portal/group/platform/administrators/navigation.xml
> +      <name>quarantine</name>
```suggestion
      <name>dlp-quarantine</name>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/conf/quarantine/portal/group/platform/administrators/navigation.xml
> +      <label>#{administration.quarantine.label}</label>
```suggestion
      <label>#{administration.dlp.quarantine.label}</label>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/conf/quarantine/portal/group/platform/administrators/navigation.xml
> +      <page-reference>group::/platform/administrators::quarantine</page-reference>
```suggestion
      <page-reference>group::/platform/administrators::dlp-quarantine</page-reference>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/conf/quarantine/portal/group/platform/administrators/pages.xml
> +    <name>quarantine</name>
```suggestion
    <name>dlp-quarantine</name>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/conf/quarantine/portal/group/platform/administrators/pages.xml
> +    <title>Quarantine</title>
```suggestion
    <title>Dlp Quarantine</title>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/conf/quarantine/portal/group/platform/administrators/pages.xml
> +        <application-ref>quarantine</application-ref>
```suggestion
        <application-ref>dlp-quarantine</application-ref>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/conf/quarantine/portal/group/platform/administrators/pages.xml
> +        <portlet-ref>quarantinePortlet</portlet-ref>
```suggestion
        <portlet-ref>dlpQuarantinePortlet</portlet-ref>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/conf/quarantine/portal/group/platform/administrators/pages.xml
> +      <title>Quarantine Administration</title>
```suggestion
      <title>Dlp Quarantine Administration</title>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/gatein-resources.xml
> +      <path>/javascript/quarantine.bundle.js</path>
```suggestion
      <path>/javascript/dlpQuarantine.bundle.js</path>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/portlet.xml
> +      <value>/quarantine.html</value>
```suggestion
      <value>/dlpQuarantine.html</value>
```

2020-12-22 13:52 UTC, azayati commented on apps/portlet-quarantine/src/main/webapp/WEB-INF/web.xml
> +  <display-name>quarantine</display-name>
```suggestion
  <display-name>dlp-quarantine</display-name>
```

2020-12-22 16:36 UTC, azayati approved these changes, later dismissed
LGTM after QA validation

2020-12-23 10:20 UTC, azayati approved these changes
LGTM

2020-12-23 10:21 UTC, merged