Task-37850: Integrate the DLP keywords file via UI
exoplatform/ecms pull request #1089
Opened 2021-01-25 10:07 UTC by AzmiTouil

2021-01-25 10:45 UTC, rdenarie approved these changes

2021-01-27 07:46 UTC, rdenarie requested changes

2021-01-27 07:46 UTC, rdenarie commented on core/connector/src/main/java/org/exoplatform/ecm/connector/dlp/FileDlpConnector.java
> +    }
Could we put that at upper level, in DlpConnector, with a function named getKeywords ?
So that, it could be exploited by all connectors implementation ?

In addition, I think that the variable dlpKeyword should be declared at global level.

2021-01-27 16:37 UTC, AzmiTouil commented on core/connector/src/main/java/org/exoplatform/ecm/connector/dlp/FileDlpConnector.java
> +    }
Done!

2021-01-27 17:07 UTC, rdenarie commented on core/connector/src/main/java/org/exoplatform/ecm/connector/dlp/FileDlpConnector.java
> +    }
I want to say 
the variable dlpKeyword should NOT be declared at global level.
Sorry

So to complete : getKeyword should be in DlpService
And we should NOT have a variable named dlpKeyword in FileDlpConnector

2021-01-28 12:13 UTC, AzmiTouil commented on core/connector/src/main/java/org/exoplatform/ecm/connector/dlp/FileDlpConnector.java
> +    }
Done!

2021-01-28 13:30 UTC, rdenarie approved these changes

2021-01-29 15:42 UTC, merged