Task-39920: Rename the security folder to Quarantine and update icon
exoplatform/ecms pull request #1094
Opened 2021-01-26 16:17 UTC by AzmiTouil

2021-03-01 17:13 UTC, rdenarie submitted a review, later dismissed

2021-03-02 08:22 UTC, rdenarie approved these changes

2021-03-02 10:13 UTC, rdenarie requested changes

2021-03-02 10:13 UTC, rdenarie commented on ecm-wcm-extension/src/main/webapp/WEB-INF/conf/dms-extension/dms/dlp-configuration.xml
>                <string>*:/platform/administrators</string>
```suggestion
              <string>*:/platform/dlp</string>
```

2021-03-02 11:00 UTC, rdenarie approved these changes

2021-03-03 09:32 UTC, rdenarie requested changes
The views for the dlp drive should be 
<string>List</string>
instead 
<string>Admin, List</string>

2021-03-03 10:02 UTC, rdenarie approved these changes

2021-03-03 14:30 UTC, azayati approved these changes
LGTM

2021-03-03 16:59 UTC, merged