TASK-42087: fixed spaces accesibility when creating a symilink from drives application
exoplatform/ecms pull request #1392
Opened 2021-08-12 08:26 UTC by nidhalnidhal

Before this fix , when creating a symilink from drives application , an administrator has full access to application spaces even the ones which he is not a member of . So i fixed this by filtering the tree entries when selecting "spaces" from the symilink creation popup in order to keep only the spaces where the administrator is a member.

2021-08-12 14:20 UTC, rdenarie requested changes
We should wait to continue this one.
I'm not sure it is a bug

2021-08-16 16:52 UTC, ahamdi requested changes

2021-08-16 16:52 UTC, ahamdi commented on core/webui/src/main/java/org/exoplatform/ecm/webui/tree/UINodeTreeBuilder.java
> +           if ((space == null) || (space!=null) && (spaceService.isMember(space,currentUser))) {
```suggestion
           if ((space == null) || (space != null && spaceService.isMember(space,currentUser))) {

```

2021-08-16 16:52 UTC, ahamdi commented on core/webui/src/main/java/org/exoplatform/ecm/webui/tree/UINodeTreeBuilder.java
>    private List<Node> filfer(final NodeIterator iterator) throws Exception{
```suggestion
  private List<Node> filter(final NodeIterator iterator) throws Exception{

```

2022-12-19 09:21 UTC, closed without merging