Task-48155:Cancel button is badly displayed in Confirmation popup
exoplatform/ecms pull request #1415
Opened 2021-08-25 08:34 UTC by lbengayed

2021-08-31 07:03 UTC, rdenarie requested changes
Can you rebase your PR in order to have only your commit ?
Thanks

2021-08-31 08:42 UTC, lbengayed commented
> Can you rebase your PR in order to have only your commit ?
> Thanks

done!

2021-08-31 08:53 UTC, rdenarie requested changes

2021-08-31 08:53 UTC, rdenarie commented on apps/portlet-documents/src/main/webapp/vue-app/legacy-composer-attachments/components/ExoDropdownMenu.vue
> +      class="folderActionsMenuItem  delete"
```suggestion
      class="folderActionsMenuItem delete"
```

2021-08-31 08:53 UTC, rdenarie commented on apps/portlet-documents/src/main/webapp/vue-app/legacy-composer-attachments/components/ExoDropdownMenu.vue
> +      class="folderActionsMenuItem  rename"
```suggestion
      class="folderActionsMenuItem rename"
```

2021-08-31 08:53 UTC, rdenarie commented on apps/resources-wcm/src/main/webapp/skin/less/ecms/portlets/attachments/legacyComposerAttachments.less
> +                    color: #ffffff!important;
Does important is necessary here ?

2021-08-31 08:53 UTC, rdenarie commented on apps/resources-wcm/src/main/webapp/skin/less/ecms/portlets/attachments/legacyComposerAttachments.less
> +                  background-image: linear-gradient(to bottom, @primaryColor, @primaryColor)!important;
Does important is necessary here ?

2021-09-01 10:54 UTC, lbengayed commented on apps/resources-wcm/src/main/webapp/skin/less/ecms/portlets/attachments/legacyComposerAttachments.less
> +                    color: #ffffff!important;
done!

2021-09-01 10:55 UTC, lbengayed commented on apps/resources-wcm/src/main/webapp/skin/less/ecms/portlets/attachments/legacyComposerAttachments.less
> +                  background-image: linear-gradient(to bottom, @primaryColor, @primaryColor)!important;
done!

2021-09-01 13:38 UTC, rdenarie approved these changes

2021-09-01 13:40 UTC, merged