Task-48942: the comment for the versions is added to the activity of the initial document (copied/pasted)
exoplatform/ecms pull request #1593
Opened 2022-01-05 12:59 UTC by wassimmhamdi

Problem: The comment of the version of the documentY is added in the activity of the documentX
Fix: Version comment of documentY are added to the correct activity of documentY

2022-01-05 17:13 UTC, rdenarie requested changes
Can you rebase your PR and resolv the conflict ?
Thanks

2022-01-06 09:46 UTC, rdenarie requested changes

2022-01-06 09:46 UTC, rdenarie commented on core/webui-explorer/src/main/java/org/exoplatform/ecm/webui/component/explorer/UIDocumentAutoVersionForm.java
> +            if (isFolder) {
Please check formatting (indentation is not ok)

2022-01-06 09:46 UTC, rdenarie commented on core/webui-explorer/src/main/java/org/exoplatform/ecm/webui/component/explorer/UIDocumentAutoVersionForm.java
> +
add a test if(destNode!=null) {

2022-01-06 13:35 UTC, wassimmhamdi commented on core/webui-explorer/src/main/java/org/exoplatform/ecm/webui/component/explorer/UIDocumentAutoVersionForm.java
> +
I did it

2022-01-06 13:49 UTC, rdenarie requested changes

2022-01-06 13:49 UTC, rdenarie commented on core/webui-explorer/src/main/java/org/exoplatform/ecm/webui/component/explorer/UIDocumentAutoVersionForm.java
>          Utils.removeReferences(destNode);
this part should be also in the if

2022-01-06 16:21 UTC, rdenarie approved these changes

2022-01-06 16:21 UTC, merged