Task-51341: many emails received after editing a watched document.
exoplatform/ecms pull request #1659
Opened 2022-02-18 15:01 UTC by Montassar-Hamadi

Problem: Before this fix, when editing a watched file from users. The watcher was receiving many emails indicating that there is changes on the file.SO this problem occurred because the process of observation was on the node and not the child node which is the jcr:content, therefore, any action that happens in the file, can change many properties even if we open and close the file without changing it. So many events fired and On every event, there's an email.
Fix: In this fix, we changed the process of the observation on the content of the file and we let the list of watchers in property EMAIL_WATCHERS_PROP of the watched file. So  any changes in the content of the watched file will fire an event which be received by the EmailNotifyCloudDocumentListener and finally this last will send  one email to each watcher if exist .

2022-02-21 15:47 UTC, rdenarie requested changes

2022-02-21 15:47 UTC, rdenarie commented on core/webui-clouddrives/src/main/java/org/exoplatform/services/cms/clouddrives/webui/watch/WatchCloudDocumentServiceImpl.java
> +    if (listener != null && documentNode.isNodeType(NodetypeConstant.NT_FILE)
Can you explain why you changed this test ?

2022-02-21 15:47 UTC, rdenarie commented on core/webui-clouddrives/src/main/java/org/exoplatform/services/cms/clouddrives/webui/watch/EmailNotifyCloudDocumentListener.java
> +    } else if (node.isNodeType(NodetypeConstant.NT_FILE)
Can you explain why you changed this test ?

2022-02-23 10:42 UTC, rdenarie requested changes
Before the fix, if createMessage or sendMessage throw an error, the for execution continue, and the other users of the list are notified
After the fix, if createMessage or sendMessage throw an error, the for execution stops, and the other users of the list are not notified.

Please modify the behaviour, so that the try in inside the for

2022-02-23 12:59 UTC, rdenarie requested changes

2022-02-23 12:59 UTC, rdenarie commented on core/webui-clouddrives/src/main/java/org/exoplatform/services/cms/clouddrives/webui/watch/EmailNotifyCloudDocumentListener.java
> +          LOG.error("jcr error occured", e);
```suggestion
          LOG.error("Unable to get node location", e);
```

2022-02-23 14:30 UTC, rdenarie approved these changes

2022-02-23 14:31 UTC, rdenarie requested changes
Can you fix the sonar issue ?

2022-02-24 08:18 UTC, rdenarie requested changes
What if NodeLocation.getNodeByLocation generate an error ?

Your previous solution was better. You just had to extract 
`try {
        Message message = createMessage(receiver, messageConfig);
        mailService.sendMessage(message);
      } catch (Exception e) {`
in a submethod
Can you rollback your last modification ?

2022-02-24 09:28 UTC, Montassar-Hamadi commented
> 

What do you suggest as a name for the submethod??

2022-02-24 16:57 UTC, rdenarie approved these changes

2022-02-24 16:57 UTC, merged