Task-58643: Related the attached file thumbnails to attachment file extension
exoplatform/ecms pull request #1813
Opened 2022-06-30 16:51 UTC by sofyenne

ISSUE : when user create process and attached a file all attached file thumbnails displayed as media , the problem is when create a copy of attachment file can't extract the extension from the copy name .
FIX : extract the extension from the original node name

2022-07-01 13:00 UTC, ahamdi requested changes

2022-07-01 13:00 UTC, ahamdi commented on core/services/src/main/java/org/exoplatform/services/cms/impl/Utils.java
> +    if(ret.indexOf(".") > -1 && ret.indexOf(".") != ret.lastIndexOf(".") ){
You can just substring the extension in the beginning of the cleanup process and then do the cleanup includin hg the dot (.) character.

2022-07-01 13:00 UTC, ahamdi commented on core/services/src/test/java/org/exoplatform/services/cms/impl/UtilsTest.java
> +    assertEquals(titleClean1,"test _ test");
why there are spaces before/after filename ?

2022-07-04 14:25 UTC, sofyenne commented on core/services/src/main/java/org/exoplatform/services/cms/impl/Utils.java
> +    if(ret.indexOf(".") > -1 && ret.indexOf(".") != ret.lastIndexOf(".") ){
Done !

2022-07-04 14:26 UTC, sofyenne commented on core/services/src/test/java/org/exoplatform/services/cms/impl/UtilsTest.java
> +    assertEquals(titleClean1,"test _ test");
done ! space removed !

2022-07-04 15:54 UTC, ahamdi approved these changes

2022-07-04 21:52 UTC, merged