Task-58742: Retrieve dynamically drive connectors
exoplatform/ecms pull request #1818
Opened 2022-07-07 10:47 UTC by abenmbarek

2022-07-13 16:20 UTC, azayati requested changes
you should move Google Drive.png and One Drive.png to the addon

2022-07-13 16:45 UTC, azayati requested changes

2022-07-13 16:45 UTC, azayati commented on apps/portlet-clouddrives/src/main/webapp/WEB-INF/gatein-resources.xml
> +      </depends>-->
this comment should be removed and you should verify if CloudDrivePortlet need to be removed.

2022-07-13 16:45 UTC, azayati commented on apps/portlet-clouddrives/src/main/webapp/WEB-INF/gatein-resources.xml
> +        <module>cloudDriveUtils</module>
is it needed to add cloudDriveUtils as dependency for the CloudDriveSettingsPortlet ?

2022-07-13 16:45 UTC, azayati commented on apps/portlet-clouddrives/src/main/webapp/WEB-INF/gatein-resources.xml
> +      </depends>-->
remove this comment

2022-07-13 16:45 UTC, azayati commented on apps/portlet-clouddrives/src/main/webapp/WEB-INF/gatein-resources.xml
> +        <module>cloudDrives</module>
s it needed to add cloudDrives as dependency for the CloudDriveSettingsPortlet ?

2022-07-13 16:45 UTC, azayati commented on apps/portlet-clouddrives/src/main/webapp/skin/clouddrive.css
> +	color: #4d5466 !important;
use appropriate color variable please and ensure file indentation

2022-07-13 16:45 UTC, azayati commented on core/webui-clouddrives/src/main/resources/locale/clouddrive/CloudDrive_en.xml
> +      <NoConnector>No personal drive connector available</NoConnector>
```suggestion
      <noConnector>No personal drive connector available</noConnector>
```

2022-07-13 16:45 UTC, azayati commented on ext/clouddrives-gdrive/webapp/src/main/webapp/WEB-INF/gatein-resources.xml
> -  <!-- Javascript for Cloud Drive support of Google Drive -->
the whole file should be removed IMO

2022-07-13 16:45 UTC, azayati commented on ext/clouddrives-onedrive/webapp/src/main/webapp/WEB-INF/conf/configuration.xml
> -  <!-- One Drive namespace for use within JCR -->
the whole file should be removed IMO

2022-07-13 16:45 UTC, azayati commented on ext/clouddrives-gdrive/webapp/src/main/webapp/WEB-INF/conf/configuration.xml
> -  <!-- Google Drive namespace for use within JCR -->
the whole file should be removed IMO

2022-07-13 16:45 UTC, azayati commented on ext/clouddrives-onedrive/webapp/src/main/webapp/WEB-INF/gatein-resources.xml
> -  <!-- Javascript for Cloud Drive support of One Drive -->
the whole file should be removed IMO

2022-07-14 14:32 UTC, abenmbarek commented on apps/portlet-clouddrives/src/main/webapp/WEB-INF/gatein-resources.xml
> +        <module>cloudDriveUtils</module>
yep it's needed to use the getUserDrive function under /js/cloudDriveService.js

2022-07-14 14:34 UTC, abenmbarek commented on apps/portlet-clouddrives/src/main/webapp/WEB-INF/gatein-resources.xml
> +        <module>cloudDrives</module>
yep it's used in every cloudDrive config js files

2022-07-14 14:37 UTC, abenmbarek commented on apps/portlet-clouddrives/src/main/webapp/skin/clouddrive.css
> +	color: #4d5466 !important;
this indentation is used in the whole file so i respected its indentation

2022-07-14 14:38 UTC, abenmbarek commented on apps/portlet-clouddrives/src/main/webapp/skin/clouddrive.css
> +	color: #4d5466 !important;
it's a css file so we cannot use color variables from variables.less

2022-07-18 10:10 UTC, azayati approved these changes
LGTM

2022-07-18 11:54 UTC, merged