fix : Fix lost extension after renaming a document - EXO-60015
exoplatform/ecms pull request #1901
Opened 2022-10-10 14:49 UTC by sofyenne

Prior to change there is a regression caused by https://github.com/exoplatform/documents/pull/416, so the modification is reverted, no need to change the title since it is a property that does not need to be cleaned nor escaped its illegal JCR characters.

2022-10-18 16:20 UTC, azayati requested changes
see review

2022-10-18 16:20 UTC, azayati commented on core/services/src/main/java/org/exoplatform/services/cms/impl/Utils.java
> +    String extension ="" ;
```suggestion
    String extension = "" ;
```

2022-10-19 08:41 UTC, sofyenne commented on core/services/src/main/java/org/exoplatform/services/cms/impl/Utils.java
> +    String extension ="" ;
done !

2022-10-19 13:01 UTC, azayati requested changes
you need to change the source branch on feature/maintenance not develop

2022-10-19 15:24 UTC, azayati approved these changes
LGTM

2022-10-19 15:25 UTC, merged