feat : reorganize application registry list - EXO-61480 - Meeds-io/MPIs#37
exoplatform/ecms pull request #1970
Opened 2023-01-04 10:28 UTC by sofyenne

This change is going to add the document portlet under the tools application category

2023-01-05 15:48 UTC, azayati requested changes

2023-01-05 15:48 UTC, azayati commented on ecm-wcm-extension/src/main/webapp/WEB-INF/conf/wcm-extension/portal/application-registry-configuration.xml
> +                      </collection>
separate the tags

2023-01-05 18:09 UTC, sofyenne commented on ecm-wcm-extension/src/main/webapp/WEB-INF/conf/wcm-extension/portal/application-registry-configuration.xml
> +                      </collection>
done !

2023-01-06 10:32 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-01-06 10:32 UTC, azayati approved these changes
LGTM

2023-01-06 10:40 UTC, merged