fix: Preview image are not displayed in activity -EXO-60824
exoplatform/ecms pull request #1997
Opened 2023-02-09 13:19 UTC by akhanfir

Prior to this change, when move image of an activity from Activity Stream Documents to another folder, the image of this activity does not show up in the activities page After this change, the moved image is displayed in the activities page.

2023-02-10 13:49 UTC, ahamdi requested changes
Could you add a Unit test for the new function ?

2023-02-14 16:20 UTC, azayati requested changes

2023-02-14 16:20 UTC, azayati commented on pom.xml
> +    <org.exoplatform.platform-ui.version>6.5.x-exo-SNAPSHOT</org.exoplatform.platform-ui.version>
this should not be changed

2023-02-16 08:46 UTC, ahamdi requested changes

2023-02-16 08:46 UTC, ahamdi commented on pom.xml
> +    <org.exoplatform.social.version>6.5.x-exo-SNAPSHOT</org.exoplatform.social.version>
@akhanfir Could you revert this change ?

2023-02-16 09:32 UTC, ahamdi approved these changes

2023-02-16 10:36 UTC, azayati approved these changes
LGTM

2023-02-16 10:36 UTC, merged