[ECMS-6069] Send many emails when user watch a edited document
exoplatform/ecms pull request #865
Opened 2015-12-02 15:00 UTC by AtiaZ

fix description : 
Send just one email when making changes in the document metadata and after clicking on "Save & Close" or after clicking on "Save".

2017-01-16 08:18 UTC, thomasdelhomenie requested changes

2017-01-16 08:18 UTC, thomasdelhomenie commented on core/services/src/main/java/org/exoplatform/services/cms/watch/impl/EmailNotifyListener.java
> +    if (arg0.getSize() > 5) {
Why 5 ?
It should probably be set in a constant, and add some comments.

2017-01-17 15:54 UTC, boubaker requested changes
Please make the send email async.

2017-01-23 10:11 UTC, AtiaZ commented
Replaced by https://github.com/exodev/ecms/pull/264

2017-01-23 10:11 UTC, closed without merging